#!/usr/bin/env bash

scriptDir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $scriptDir/generic_routines.sh
source $scriptDir/lsf.sh

usageOpts="[ -c <command string> ] \
           [ -w <working directory, default current working directory> ] \
           [ -m <memory in Mb, defaults to cluster default> ] \
           [ -p <number of cores, defaults to cluster default> ] \
           [ -j <job name, defaults to cluster default> ] \
           [ -g <job group name, defaults to cluster default> ] \
           [ -l <log prefix, no logs written by default> ] \
           [ -e <clean up log files after monitored run? Defaults to no> ] \
           [ -n <monitor submitted job? Defaults to yes> ] \
           [ -s <monitor style: 'status' for job status updates on polling, 'std_out_err' to report ongoing content of logs (where used). Defaults to std_out_err> ] \
           [ -f <poll frequency in seconds if job is monitored. Defaults to 10.> ] \
           [ -q <lsf queue, defaults to cluster default> ] \
           [ -v <name of the conda environment in which to run the job> ]"

usageOpts=$(echo -e "$usageOpts" | tr -s " ")
usage() { echo "Usage: $0 $usageOpts"; }

# Parse arguments

commandString=
workingDir=
memory=
cores=
jobName=
queue=
jobGroupName=
logPrefix=
logCleanup=no
monitorJob=yes
pollFreqSecs=10
monitorStyle=std_out_err
prioritise=no

while getopts ":c:w:m:p:j:g:l:e:n:f:q:s:r:v:" o; do
    case "${o}" in
        c)
            commandString=${OPTARG}
            ;;
        w)
            workingDir=${OPTARG}
            ;;
        m)
            memory=${OPTARG}
            ;;
        p)
            cores=${OPTARG}
            ;;
        j)
            jobName=${OPTARG}
            ;;
        q)
            queue=${OPTARG}
            ;;
        g)
            jobGroupName=${OPTARG}
            ;;
        l)
            logPrefix=${OPTARG}
            ;;
        e)
            logCleanup=${OPTARG}
            ;;
        n)
            monitorJob=${OPTARG}
            ;;
        f)
            pollFreqSecs=${OPTARG}
            ;;
        s)
            monitorStyle=${OPTARG}
            ;;
        r)
            prioritise=${OPTARG}
            ;;
        v)
            condaEnv=${OPTARG}
            ;;
        *)
            usage
            exit 0
            ;;
    esac
done

# Submit the jobs

lsfJobId=$(lsf_submit "$commandString" "$queue" "$jobName" "$memory" "$cores" "$jobGroupName" "$workingDir" "$logPrefix" "$prioritise" "$condaEnv")
submitStatus=$?

if [ "$submitStatus" -ne "0" ] && [ -n "$lsfJobId" ]; then
    die "Job submission failed, status is $submitStatus"
else
    echo "Job submission succeeded, received job ID $lsfJobId"
    
    if [ "$monitorJob" = 'yes' ]; then
        logFile=
        if [ -n "$logPrefix" ]; then
            logFile=${logPrefix}.out
        fi 

        lsf_monitor_job "$lsfJobId" "$pollFreqSecs" "$logFile" "$monitorStyle" "$logCleanup"

        if [ $? -ne 0 ]; then
            die "Command \"$commandString\" failed"
        fi
    fi
fi
